package DataAndAlgoL.Chp3LinkedLists;
/*
 * HOW TO CHECK IS LINKED LIST IS PALINDROME OR NOT
 * 
 * ALGORITHM:
 * 1. GET THE MIDDLE OF THE LINKED LIST 
 * 2. REVERSE THE SECOND HALF OF THE LINKED LIST
 * 3.COMPARE THE 1ST HALF WITH THE 2ND HALF
 * 4. CONSTRUCT THE ORIGINAL LINKED LIST BY REVERSING THE SECOND HALF AGAIN AND ATTACHING IT BACK TO THE 1ST HALF 
 */
public class Problem39 {
    public static void main(String[] args) {
        
    }

    
}
